[server]
host = "127.0.0.1"
port = 4000
anonym_allowed = true

[frontend]
domen = "https://ocean-mandela.info"

[postgres]
host = "localhost"
port = 5432
username = "ocean"
password = ""
database = "ocean"

[telegram_bot]
token = ""
url = "https://api.telegram.org"
channel = ""
admin_chat_id = ""
enabled = true

[watchdog]
enabled = false
anonym_token = ""
